# Site settings
title: Mirza's blog
description: Foo
author: Mirza
baseurl: /
url: https://blog.arnaut.me

# Social Profiles
github_username: arunoruto
linkedin_username: mirza-arnaut-78589b14b
orcid: 0000-0002-1631-7083
# twitter_username:
# facebook_username:
# instagram_username:

# Build settings
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
markdown: kramdown
paginate: 5
paginate_path: /posts/page:num/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Misc settings
